from __future__ import division
from struct import unpack,calcsize
import math
import numpy
import Image
import os
import debug

def readhgt(filename):
	debug.write("Opening %s" % (filename))
	f = open(filename, "rb")
	hgt_string = f.read()

	tilesize = int(math.sqrt(len(hgt_string)/2))
	if tilesize == 1201:
		resolution = 3
	elif tilesize == 3601:
		resolution = 1
	else:
		raise Exception('Error: Can only support 3" and 1" data')

	debug.write(" Tile size %d Resolution %d\"" % (tilesize, resolution))

	hgt_2darray = numpy.flipud(((numpy.fromstring(string=hgt_string, dtype='int16')).byteswap()).reshape(tilesize,tilesize))
	return tilesize, hgt_2darray

def gethgt(hgt_2darray, lat, lon):
	try:
		data = hgt_2darray[lat, lon]
		return data
	except:
		print "No height for %d,%d" % (lat, lon)
		return 0



def make_scad(data, outputfile, scale_x, scale_y, scale_z):
	datafile = outputfile + ".dat"
	fd = open(datafile, "w")
	for y in range(data.shape[1]):
		for x in range(data.shape[0]):
			fd.write("%f " % (data[x,y]))
		fd.write("\n")
	fd.close()
	print "Saved data %s" % (datafile)

	fd = open(outputfile, "w")
	fd.write("//\n")
	fd.write("// Generated by generate.py\n")
	fd.write("//\n")
	fd.write("union() { \n")
	fd.write("   scale([%f, %f, %f])\n" % (scale_x, scale_y, scale_z))
	fd.write("      surface(file = \"%s\", center = true, convexity = 5);\n" % (os.path.basename(datafile)))
	fd.write("};\n")
	fd.close()
	print "Saved SCAD %s" % (outputfile)

def make_jpg(data, outfile):
	ppix = numpy.array(data)
	im = Image.fromarray(ppix)

	#imrgb = Image.merge('RGB', (im,im,im))
	imrgb = im.convert("RGB")

	imrgb.save(outfile)
	print "Saved JPG %s (Size=%dx%d)" % (outfile, data.shape[0], data.shape[1])
